# Generated by Django 4.1.1 on 2022-10-05 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coat_color', models.CharField(max_length=1000)),
                ('coat_pattern', models.CharField(max_length=1000)),
            ],
        ),
    ]
