# Generated by Django 4.1.1 on 2022-10-05 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='color',
            name='coat_pattern',
        ),
        migrations.AddField(
            model_name='color',
            name='colors',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='color', to='main_app.breed'),
        ),
        migrations.AddField(
            model_name='color',
            name='length',
            field=models.IntegerField(default=0),
        ),
    ]
