# Generated by Django 4.1.1 on 2022-10-05 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_color_colors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='color',
            name='length',
        ),
        migrations.AddField(
            model_name='color',
            name='pattern',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
