# Generated by Django 4.1.1 on 2022-10-05 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_remove_color_length_color_pattern'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='coat_color',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
