# Generated by Django 4.1.1 on 2022-10-05 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_alter_color_coat_color'),
    ]

    operations = [
        migrations.RenameField(
            model_name='color',
            old_name='coat_color',
            new_name='coat',
        ),
    ]
