# Generated by Django 4.1.1 on 2022-10-05 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_rename_coat_color_color_coat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='coat',
            field=models.CharField(max_length=100),
        ),
    ]
