# Generated by Django 4.1.1 on 2022-10-05 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_alter_color_coat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='coat',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
