# Generated by Django 4.1.1 on 2022-10-06 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_alter_color_coat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('traits', models.CharField(max_length=1000)),
                ('temperament', models.ManyToManyField(to='main_app.color')),
            ],
        ),
    ]
