# Generated by Django 4.1.1 on 2022-10-06 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_personality'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personality',
            name='temperament',
        ),
        migrations.CreateModel(
            name='Characteristics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('traits', models.CharField(max_length=300)),
                ('temperament', models.CharField(max_length=300)),
                ('characteristics', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characteristics', to='main_app.breed')),
            ],
        ),
        migrations.AddField(
            model_name='personality',
            name='characteristics',
            field=models.ManyToManyField(to='main_app.characteristics'),
        ),
    ]
